services:
  - type: web
    name: athletIA2
    env: docker
    buildCommand: ./mvnw clean package -DskipTests
    envVars:
      - key: SPRING_DATA_MONGODB_URI
        sync: false
      - key: JAVA_VERSION
        value: 21
